In [1]:
import torch
from torchmetrics import PearsonCorrCoef
from module.metircs import PearsonR

In [2]:
x = torch.tensor([[3, -0.5, 2, 7],
                  [3, -0.5, 2, 7]])
y = torch.tensor([[2.5, 0.0, 2, 8],
                  [2.5, 0.0, 2, 8]])

In [37]:
x.shape

torch.Size([2, 4])

In [29]:
x = torch.randn([2,896])

In [30]:
x

tensor([[-1.6136,  0.1045,  0.4275,  ..., -0.0413, -1.6732,  1.0866],
        [ 0.2266, -2.2747,  0.3798,  ..., -0.4522,  1.2958, -0.8201]])

In [7]:
torch.sum(torch.mul(x, y), dim=1)

tensor([67.5000, 67.5000])

In [23]:
torch.mul(x, y)

tensor([[ 7.5000, -0.0000,  4.0000, 56.0000]])

In [12]:
x.shape

torch.Size([4, 4])

In [22]:
x.shape

torch.Size([4, 1])

In [3]:
pearsonr = PearsonR(num_targets=2, summarize=False)

In [4]:
pearsonr.update(x, y)

In [5]:
pearsonr.compute()

tensor([0.9849, 0.9849])

In [6]:
pearsonr.reset()

In [22]:
product

NameError: name 'product' is not defined